version: "2"
services:
  mysql:
    container_name: mysql
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
      MYSQL_DATABASE: "tournament_db"
    network_mode: host
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  tournament_service:
    container_name: tservice
    image: "ivanthescientist/tournament_service"
    network_mode: host
    restart: always
    depends_on:
      - mysql